# Generated by Django 2.2.1 on 2020-03-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('birthDate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=15, unique=True)),
                ('passWord', models.CharField(max_length=15)),
            ],
        ),
    ]
